name: challenge

on: push

jobs:
    job1:
        name: ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: date 
    job2:
        name: windows
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
               run: date
    job3:
        name: windows
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
               run: date
    job4:
        needs:[job1,job2,job3]
        name: windows
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
               run: date